/*************************************************************************
 * File: InsufficientFunds.h
 * Author: xinyiHsu，B11130008@mail.ntust.edu.tw
 * Create Date: 2023-05-31
 * Editor: xinyiHsu，B11130008@mail.ntust.edu.tw
 * Update Date: 2023-05-31
 * Description: Handling errors generated by the function withdraw(double).
 *************************************************************************/
#pragma once

class InsufficientFunds
{

};
