/*************************************************************************
 * File: NegativeDeposit.h
 * Author: xinyiHsu，B11130008@mail.ntust.edu.tw
 * Create Date: 2023-05-31
 * Editor: xinyiHsu，B11130008@mail.ntust.edu.tw
 * Update Date: 2023-05-31
 * Description: Handling errors generated by the function deposit(double).
 *************************************************************************/
#pragma once

class NegativeDeposit
{

};
